### ISSUE TITLE
6. Show connected wallet info

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch10.buidlguidl.com#5]
## Goal

When a user connects to the dApp, let's display 2 things:

1. Is the connected address a member of the batch? (is the in the allowList)
2. Is the connected address already checked in?

Feel free to place that info whenever you want. It could be just some icons that show next to the wallet for members.

For more info about the contract: #10

**Comment by Lukman-01** [comment]
Good morning Sir @phipsae, I have raised a PR for this issue, kindly review.

**Comment by phipsae** [comment]
Thank you very much! I gonna review it soon.
