### ISSUE TITLE
5. Get the check-in count from the BatchRegistry contract

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch10.buidlguidl.com#6]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: #10

**Comment by Superior212** [comment]
I'm working on this issue

**Comment by Superior212** [comment]
@phipsae I'm Done working on it 
kindly review 
thanks

**Comment by phipsae** [comment]
Thank I gonna review it soon.
