### ISSUE TITLE
3. Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by phipsae** [BuidlGuidl/batch10.buidlguidl.com#8]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: `Batch #10`
- subtitle: Whatever you feel appropriate :)

**Comment by Favvie** [comment]
I'd like to work on this issue.

**Comment by michojekunle** [comment]
@Favvie 
![image](https://github.com/user-attachments/assets/ef915c71-2921-45fa-a3b1-261446bfa532)

**Comment by phipsae** [comment]
@Favvie, that would be nice!

**Comment by Superior212** [comment]
I think this issue is being fixed, it suppose to be closed
